CREATE DATABASE BAMAZON;
USE BAMAZON;
CREATE TABLE PRODUCTS (Auto_INCREMENT,
id  INT Not NULL,
productName VARCHAR (100),
departmentName VARCHAR (100),
stockQuantity VARCHAR (100),
price VARCHAR (100),
);
